// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVoHWH5XI2Xe4k2Sz_u_M2YXCUwGcgano',
    appId: '1:70367155908:web:39c1344d65ecce16141b91',
    messagingSenderId: '70367155908',
    projectId: 'danim-3439e',
    authDomain: 'danim-3439e.firebaseapp.com',
    storageBucket: 'danim-3439e.appspot.com',
    measurementId: 'G-VXZTLNFY84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVEQpLINJPRz139TIVwmOqN-QUerr3Fms',
    appId: '1:70367155908:android:ba936316358226d0141b91',
    messagingSenderId: '70367155908',
    projectId: 'danim-3439e',
    storageBucket: 'danim-3439e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBnwLWZuvDpE3dGKXn4QR9RwhVkK6t1Cs',
    appId: '1:70367155908:ios:2a4e5e0021b6a949141b91',
    messagingSenderId: '70367155908',
    projectId: 'danim-3439e',
    storageBucket: 'danim-3439e.appspot.com',
    iosClientId: '70367155908-db1etfvpmhkuorkq3va84nlsoq19s8ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.danim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBnwLWZuvDpE3dGKXn4QR9RwhVkK6t1Cs',
    appId: '1:70367155908:ios:2a4e5e0021b6a949141b91',
    messagingSenderId: '70367155908',
    projectId: 'danim-3439e',
    storageBucket: 'danim-3439e.appspot.com',
    iosClientId: '70367155908-db1etfvpmhkuorkq3va84nlsoq19s8ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.danim',
  );
}
